### import relevant library

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

### create the target variable

In [3]:
minimum_absent_hours = data_preprocessed['Absenteeism Time in Hours'].median()
minimum_absent_hours

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > minimum_absent_hours,
                 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets

In [6]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0                 30          0         2    1                          4   
1                 31          0         1    0                          0   
2                 31          0         0    0                          2   
3                 24          0         2    0                          4   
4                 30          0         2    1                          2   
..               ...        ...       ...  ...                        ...   
695               22          1         2    0                          8   
696               24          0         1    2                          3   
697               25          1         0    0                          8   
698               25          1         0    0                          2   
699               25          0         1    1                          2   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 16 columns]

### comment

#### It us importance that we have a balanced dataset for logistics regression i.e target have equal proportion of a 1 & 0 but some 60-40 or 55-45 is cool

In [7]:
targets.sum()/ targets.shape[0] #length

0.45571428571428574

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Distance to Work', 'Daily Work Load Average'], axis= 1)
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [9]:
data_with_targets is data_preprocessed

False

### Select the inputs for the regression

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
unscaled_features =data_with_targets.iloc[:, :-1]
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

### Standardize the features

When scaling, we will not scale the dummy variable.

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

class CustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [13]:
unscaled_features.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [14]:
col_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
col_2_scale = [x for x  in unscaled_features.columns.values if x not in col_to_omit]

In [15]:
abstm_scaler = CustomScaler(col_2_scale)  # Assuming col_2_scale is a DataFrame
scaled_features = abstm_scaler.fit_transform(unscaled_features)

In [16]:
scaled_features

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

          Pet  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [17]:
scaled_features.shape

(700, 11)

In [18]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train, y_test = train_test_split(scaled_features, targets, test_size = 0.2, random_state=42)

In [19]:
print(x_train.shape,x_test.shape)

(560, 11) (140, 11)


In [20]:
print(y_train.shape, y_test.shape)

(560,) (140,)


### Logistic regression 

In [21]:
from sklearn.linear_model import LogisticRegression

linreg = LogisticRegression()
linreg.fit(x_train, y_train)
model_prediction = linreg.predict(x_test)
model_prediction

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0])

In [22]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,

In [23]:
linreg.score(x_train, y_train)

0.7732142857142857

###  Finding the intercept and coefficients

In [24]:
linreg.intercept_

array([-1.68800249])

In [25]:
linreg.coef_

array([[ 2.90600225,  0.7548816 ,  3.08731323,  0.94700556,  0.02451849,
         0.65563825, -0.25286853,  0.25704553, -0.25145264,  0.40171316,
        -0.2957514 ]])

In [26]:
feature_names = unscaled_features.columns
feature_names

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'],
      dtype='object')

In [27]:
coefficient =  linreg.coef_

### Summmary table

In [28]:
summary_table = pd.DataFrame(columns = ['feature_names'], data = feature_names)

In [29]:
summary_table['coefficient'] = np.transpose(linreg.coef_)

summary_table

feature_names  coefficient
0                 Reason_1     2.906002
1                 Reason_2     0.754882
2                 Reason_3     3.087313
3                 Reason_4     0.947006
4              Month Value     0.024518
5   Transportation Expense     0.655638
6                      Age    -0.252869
7          Body Mass Index     0.257046
8                Education    -0.251453
9                 Children     0.401713
10                     Pet    -0.295751

In [30]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['intercept', linreg.intercept_[0]]
summmary_table = summary_table.sort_index()
summary_table

feature_names  coefficient
1                 Reason_1     2.906002
2                 Reason_2     0.754882
3                 Reason_3     3.087313
4                 Reason_4     0.947006
5              Month Value     0.024518
6   Transportation Expense     0.655638
7                      Age    -0.252869
8          Body Mass Index     0.257046
9                Education    -0.251453
10                Children     0.401713
11                     Pet    -0.295751
0                intercept    -1.688002

### Interpreting the Coefficient 

A feature is not particularly important, if its coeeficient is around 0.if its odds ratio is around 1.

A weight of 0 implies that no matter the feature value, we will multiply it by 0(in the model)

For a unit change in the standardized feature, the odds increase by a multiple equal t0 the 0dds ratio(1 = no change)

Given all features, Distance to Work, month Value, Daily Work Load Average seems to be the one that makes no difference as they their weight is far frm zero. making them have no important or impact in the model.

Looking at the reasons which are the main predictive factor.It seems when any employee have anyone of the reasons, there is a chance that they will be absent as their coefficient is greater than 0 and 0dd ration is above 1.

In [31]:
summary_table['Odds ratio'] = np.exp(summary_table.coefficient)
summary_table

feature_names  coefficient  Odds ratio
1                 Reason_1     2.906002   18.283559
2                 Reason_2     0.754882    2.127360
3                 Reason_3     3.087313   21.918110
4                 Reason_4     0.947006    2.577978
5              Month Value     0.024518    1.024822
6   Transportation Expense     0.655638    1.926372
7                      Age    -0.252869    0.776570
8          Body Mass Index     0.257046    1.293104
9                Education    -0.251453    0.777670
10                Children     0.401713    1.494383
11                     Pet    -0.295751    0.743972
0                intercept    -1.688002    0.184888

In [32]:
summary_table.sort_values('Odds ratio', ascending=False)

feature_names  coefficient  Odds ratio
3                 Reason_3     3.087313   21.918110
1                 Reason_1     2.906002   18.283559
4                 Reason_4     0.947006    2.577978
2                 Reason_2     0.754882    2.127360
6   Transportation Expense     0.655638    1.926372
10                Children     0.401713    1.494383
8          Body Mass Index     0.257046    1.293104
5              Month Value     0.024518    1.024822
9                Education    -0.251453    0.777670
7                      Age    -0.252869    0.776570
11                     Pet    -0.295751    0.743972
0                intercept    -1.688002    0.184888

### Reason 0 = No reason = The base model(whne no reason is given)

Reason 1 = Various diseases
Reason 2 = Pregnacy and given birth
Reason 3 = Poisoning
reason 4 = light diseases
The odd ratio of the reason 3 implies that there is 22 times greater than the base model that if an employee is poisoned, they will definitely be absent. if an employee is with reason 1 i.e when an employee is sick there is 19 times chances that they will be absent. Employee with who are pregnant have 2times greater to be absent as they natural phenomenon may requires medical attention and  emergency may arise that requires them to leave work and not return or they may return. People with light disease have the lowest chance of being absent. Sometimes the transport expenses and employee who have children may cause employee to be absent. sometimes their children may have complications that require their parent attention for example when their fell ill.

Using back elination, column that holds no significance should be dropped as they will not affect the model performance

### Testing the model

In 77%  of the cases,  the model will predict that there will be an excessive abstenteeism based on the data the model haven't seen before.

Obtaining the probability of excess absenteeism  

In [33]:
linreg.score(x_test, y_test)

0.7714285714285715

In [34]:
prediction_prob = linreg.predict_proba(x_test)
prediction_prob

array([[0.82382633, 0.17617367],
       [0.86071363, 0.13928637],
       [0.79418937, 0.20581063],
       [0.58674649, 0.41325351],
       [0.59047288, 0.40952712],
       [0.0784706 , 0.9215294 ],
       [0.67472738, 0.32527262],
       [0.37480563, 0.62519437],
       [0.72183578, 0.27816422],
       [0.75625756, 0.24374244],
       [0.86419682, 0.13580318],
       [0.69223869, 0.30776131],
       [0.25934972, 0.74065028],
       [0.46136628, 0.53863372],
       [0.71570213, 0.28429787],
       [0.47841848, 0.52158152],
       [0.89102932, 0.10897068],
       [0.22758282, 0.77241718],
       [0.85983121, 0.14016879],
       [0.59755422, 0.40244578],
       [0.70535717, 0.29464283],
       [0.7576082 , 0.2423918 ],
       [0.7096897 , 0.2903103 ],
       [0.70154218, 0.29845782],
       [0.86673748, 0.13326252],
       [0.16895155, 0.83104845],
       [0.59755422, 0.40244578],
       [0.60012512, 0.39987488],
       [0.76295969, 0.23704031],
       [0.59931834, 0.40068166],
       [0.

In [35]:
prediction_prob = prediction_prob[:, 1:]
prediction_prob

array([[0.17617367],
       [0.13928637],
       [0.20581063],
       [0.41325351],
       [0.40952712],
       [0.9215294 ],
       [0.32527262],
       [0.62519437],
       [0.27816422],
       [0.24374244],
       [0.13580318],
       [0.30776131],
       [0.74065028],
       [0.53863372],
       [0.28429787],
       [0.52158152],
       [0.10897068],
       [0.77241718],
       [0.14016879],
       [0.40244578],
       [0.29464283],
       [0.2423918 ],
       [0.2903103 ],
       [0.29845782],
       [0.13326252],
       [0.83104845],
       [0.40244578],
       [0.39987488],
       [0.23704031],
       [0.40068166],
       [0.12365487],
       [0.12933194],
       [0.6182887 ],
       [0.54228018],
       [0.28579392],
       [0.65097172],
       [0.29334453],
       [0.12933194],
       [0.84969171],
       [0.2088663 ],
       [0.52524396],
       [0.24104626],
       [0.62862838],
       [0.13323921],
       [0.23177082],
       [0.73803013],
       [0.77412439],
       [0.877

### Saving the model

In [37]:
import pickle

with open('model', 'wb' )as file:
    pickle.dump(linreg, file)

with open('absenteeism_scaler', 'wb') as file:
    pickle.dump('abstm_scaler', file) 